### ISSUE TITLE
Code smell - Bloaters - Data Clumps

### ISSUE THREAD

**Issue by naatii** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#23]

**Comment by revilofe** [comment]
@naatii no deberia integrarse hasta que no esté revisado.

**Comment by naatii** [comment]
a perdón

**Comment by naatii** [comment]
es que creo que nadie se está dedicando a revisar, los que están en
revisión llevan allí desde ayer entonces pues no sé
