### ISSUE TITLE
Refactoring - Simplifying Method Calls - Rename Method

### ISSUE THREAD

**Issue by DanielSaborido** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#29]

**Comment by MauriDjango** [comment]
@DanielSaborido  Hola Dani, que te parece si yo hago el review de tus issues y tu las mias?

**Comment by DanielSaborido** [comment]
Vale, pero ahora mismo no estoy en casa, te lo reviso cuando llegue
