### ISSUE TITLE
Code Smells - Change Preventers - Divergent Change

### ISSUE THREAD

**Issue by c0d3sh0rt4g3** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#35]

**Comment by naatii** [comment]
Al principio del todo pone que la cirugía de escopeta se parece a la cirugía de escopeta además de que el enlace no lleva a ninguna parte

**Comment by c0d3sh0rt4g3** [comment]
El enlace funcionará al mergear, lo del principio lo acabo de cambiar, gracias no me di cuenta.

**Comment by naatii** [comment]
perfecto pues lo pasamos ya a done?

**Comment by c0d3sh0rt4g3** [comment]
compruebame otra vez el tema de los enlaces q creo q ahora si va bien

**Comment by c0d3sh0rt4g3** [comment]
despues de eso yo creo que si se podría pasar ya a done

**Comment by c0d3sh0rt4g3** [comment]
procedo a mergear divergent con main
