### ISSUE TITLE
Refactoring - Moving Features between Objects - Remove Middle Man

### ISSUE THREAD

**Issue by F0rno** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#44]

**Comment by MauriDjango** [comment]
Juanjo ya tiene este tema en Review

**Comment by F0rno** [comment]
@MauriDjango 😭

**Comment by MauriDjango** [comment]
Tienes que integrar este issue en la tabla principal

**Comment by MauriDjango** [comment]
@AdriFdezz

**Comment by naatii** [comment]
@MauriDjango Sigue tenindolo esto juanjo? o como porque no lo tiene asignado ni nada no entiendo
