### ISSUE TITLE
Refactoring - Simplifying Method Calls - Introduce Parameter Object

### ISSUE THREAD

**Issue by Albertopinero** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#50]

**Comment by naatii** [comment]
Debes añadir como enlace los enlaces que haya en la web para ello debes hacerlo así [Extract Method](y aquí el enlace)

**Comment by AdriFdezz** [comment]
Problema extraño donde el issue tiene un nombre y luego el archivo de md tiene un nombre completamente diferente y no existe dentro de la pagina refactoring.guru debido a la confusion que puede crear esto procedo a cerrar este issue y crear uno con el nombre review completamente nuevo.
