### ISSUE TITLE
Refactoring - Moving Features between Objects - Extract Class

### ISSUE THREAD

**Issue by hyunxhri** [IES-Rafael-Alberti/EDES-P4.3.1-Refactoring#67]

**Comment by naatii** [comment]
Debes introducir los enlaces de la web como enlaces aquí también, están en negrita para añadirlo como enlace haz así [clase en línea](y aquí el enlace)

**Comment by hyunxhri** [comment]
> Debes introducir los enlaces de la web como enlaces aquí también, están en negrita para añadirlo como enlace haz así [clase en línea](y aquí el enlace) supongo que en los demás también te habrá pasado

Corregido, gracias
